[package]
name = "helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
secp256k1 = { version = "0.30.0", features = ["rand"] }
hex = "0.4.3"
color-eyre = "0.6.3"
sha2 = "0.10.8"
bs58 = "0.5.1"