[package]
name = "bee_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.0.0", default-features = false, features = ['std'] }
bee-vm = { path = "../../../bee-vm" }
